[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/infra/Dockerfile.subscriber"

[deploy]
startCommand = "python orchestration/subscriber.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
